on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4
        id: cache-build
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: cargo build --release

      - name: Lint
        run: cargo fmt --verbose --check

      - name: Test
        run: cargo test --verbose

  publish:
    name: Publish
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'

    needs: [lint_test]

    steps:
      - uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4
        id: cache-build
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: cargo build --release

      - name: Package
        run: cargo package

      # - name: Publish
      #   run: cargo publish

  # tf:
  #   uses: automas-dev/reusable-workflows/.github/workflows/terraform_deploy.yml@main
  #   secrets: inherit

  #   permissions:
  #     contents: write
  #     pull-requests: write

  #   concurrency:
  #     group: ${{ github.workflow }}
  #     cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60

  #   needs: [tf, lint_test]

  #   steps:
  #     - uses: actions/checkout@v5

  #     - uses: actions/setup-node@v6
  #       with:
  #         node-version: 26

  #     - name: Set package version
  #       run: npm version --no-git-tag-version $VERSION
  #       env:
  #         VERSION: ${{ needs.tf.outputs.version }}

  #     - name: Get alias from branch name
  #       id: alias
  #       run: |
  #         echo ALIAS=\"$(echo $GITHUB_HEAD_REF | tr / - | tr _ -)\" >> $GITHUB_OUTPUT

  #     - name: Build & Deploy Worker Dev
  #       uses: cloudflare/wrangler-action@v3
  #       if: github.ref != 'refs/heads/main'
  #       with:
  #         wranglerVersion: "4.88.0"
  #         apiToken: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
  #         accountId: ${{ vars.TF_VAR_ACCOUNT_ID }}
  #         command: versions upload --preview-alias ${{ steps.alias.outputs.ALIAS }}

  #     - name: Apply D1 Migrations Prod
  #       uses: cloudflare/wrangler-action@v3
  #       if: github.ref == 'refs/heads/main'
  #       with:
  #         wranglerVersion: "4.88.0"
  #         apiToken: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
  #         accountId: ${{ vars.TF_VAR_ACCOUNT_ID }}
  #         command: d1 migrations apply templog --remote

  #     - name: Build & Deploy Worker Prod
  #       uses: cloudflare/wrangler-action@v3
  #       if: github.ref == 'refs/heads/main'
  #       with:
  #         wranglerVersion: "4.88.0"
  #         apiToken: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
  #         accountId: ${{ vars.TF_VAR_ACCOUNT_ID }}
